### ISSUE TITLE
dropdown.umd.min.js incompatible with bootstrap 3

### ISSUE THREAD

**Issue by MrMarshall** [softsimon/ngx-bootrap-multiselect#396]
When downloading the package through npm, the formatting of the dropdown is not working anymore. I identified that this was caused by a different dropdown.umd.min.js.

Neighter downgrading nor upgrading works as it's downloading the same js file. I found out that the formatting is OK when bootstrap 4 is installed.

Additional information:
-angular-2-dropdown-multiselect v1.6.3
-Bootstrap v3.3.7
-Nodejs v7.7.3
-Npm v4.1.2

![image](https://user-images.githubusercontent.com/23015152/37343667-7d1343bc-26c8-11e8-8620-bf3a3ab0a803.png)

**Comment by Bailamos** [comment]
Any fix on this?

**Comment by rdicroce** [comment]
I am working around this by adding some CSS:

```css
ss-multiselect-dropdown div.dropdown-menu > a {
	display: block;
	padding: 0px 5px;
}
```
